# DataSource Config
spring:
    datasource:
        #driver-class-name: org.h2.Driver
        #schema: classpath:db/schema-h2.sql
        #data: classpath:db/data-h2.sql
        url: jdbc:mysql://3.142.82.250:3306/bibi?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: root
        password: 123456


# Logger Config
logging:
    level:
      com.neo: info
